version: '3.4'

services:
  projectmanagement_api:
    container_name: ProjectManagement_ApiService
    image: ${DOCKER_REGISTRY-}projectmanagementapi
    build:
      context: .
      dockerfile: ApiManagement/ProjectManagement_Api/Dockerfile

