version: '3.8'

services:
  s_rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=giray
      - RABBITMQ_DEFAULT_PASS=123

  s_consul:
    container_name: Consul
    image: consul:1.15.4
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp

  s_mssql:
    container_name: MsSQLServer
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
    - "5002:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Gv973041*
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    networks:
      - sqlnet

  s_mongo:
    image: mongo:6.0.5-jammy
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - "mongo_data:/data/db"
    networks:
      - graynet

  s_opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    volumes:
      - "log_data:/usr/share/opensearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
    networks:
      - graynet
    restart: unless-stopped

  graylog:
    image: graylog/graylog:5.1
    container_name: graylog
    environment: 
      GRAYLOG_PASSWORD_SECRET: "somepasswordpepper"
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 -- /docker-entrypoint.sh
    volumes:
      - "graylog_config:/config/graylog/graylog.conf:/usr/share/graylog/config/graylog.conf"
      - "graylog_data:/usr/share/graylog/data"
    networks:
      - graynet
    restart: always
    depends_on:
      s_opensearch:
        condition: service_started
      s_mongo:
        condition: service_started
    ports:
      - 9000:9000/tcp
      - 1514:1514/tcp
      - 1514:1514/udp
      - 12201:12201/tcp
      - 12201:12201/udp

  # s_identityservice:
  #   container_name: IdentityService
  #   image: girayvardal/identityservice
  #   ports:
  #     - 5003:80
  #   networks:
  #     - sqlnet


volumes:
  mongo_data:
    driver: local
  log_data:
    driver: local
  graylog_data:
    driver: local
  graylog_config:
    driver: local
  rabbitmq_data:
    driver: local



networks:
  graynet:
    driver: bridge
  sqlnet:
    driver: bridge
    
    





