// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Infrastructure;

#nullable disable

namespace ProjectManagement_Api.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230915112754_AddKanbanCreatedDate")]
    partial class AddKanbanCreatedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.KanbanCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assignee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KanbanCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Assignee = "Nancy Davloio",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Open",
                            Summary = "Analyze the new requirements gathered from the customer.",
                            Title = "BLAZ-29001"
                        },
                        new
                        {
                            Id = 2,
                            Assignee = "Andrew Fuller",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            Summary = "Improve application performance",
                            Title = "BLAZ-29002"
                        },
                        new
                        {
                            Id = 3,
                            Assignee = "Janet Leverling",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Open",
                            Summary = "Arrange a web meeting with the customer to get new requirements.",
                            Title = "BLAZ-29003"
                        },
                        new
                        {
                            Id = 4,
                            Assignee = "Janet Leverling",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            Summary = "Fix the issues reported in the IE browser.",
                            Title = "BLAZ-29004"
                        },
                        new
                        {
                            Id = 5,
                            Assignee = "Steven walker",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Review",
                            Summary = "Fix the issues reported by the customer.",
                            Title = "BLAZ-29005"
                        },
                        new
                        {
                            Id = 6,
                            Assignee = "Nancy Davloio",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Review",
                            Summary = "Fix the issues reported in Safari browser.",
                            Title = "BLAZ-29006"
                        },
                        new
                        {
                            Id = 7,
                            Assignee = "Margaret hamilt",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Close",
                            Summary = "Test the application in the IE browser.",
                            Title = "BLAZ-29007"
                        },
                        new
                        {
                            Id = 8,
                            Assignee = "Steven walker",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Validate",
                            Summary = "Validate the issues reported by the customer.",
                            Title = "BLAZ-29008"
                        },
                        new
                        {
                            Id = 9,
                            Assignee = "Margaret hamilt",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Open",
                            Summary = "Show the retrieved data from the server in grid control.",
                            Title = "BLAZ-29009"
                        },
                        new
                        {
                            Id = 10,
                            Assignee = "Janet Leverling",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            Summary = "Fix cannot open user’s default database SQL error.",
                            Title = "BLAZ-29010"
                        },
                        new
                        {
                            Id = 11,
                            Assignee = "Janet Leverling",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Review",
                            Summary = "Fix the issues reported in data binding.",
                            Title = "BLAZ-29011"
                        },
                        new
                        {
                            Id = 12,
                            Assignee = "Andrew Fuller",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Close",
                            Summary = "Analyze SQL server 2008 connection.",
                            Title = "BLAZ-29012"
                        },
                        new
                        {
                            Id = 13,
                            Assignee = "Margaret hamilt",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Validate",
                            Summary = "Validate databinding issues.",
                            Title = "BLAZ-29013"
                        },
                        new
                        {
                            Id = 14,
                            Assignee = "Margaret hamilt",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Close",
                            Summary = "Analyze grid control.",
                            Title = "BLAZ-29014"
                        },
                        new
                        {
                            Id = 15,
                            Assignee = "Steven walker",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Close",
                            Summary = "Stored procedure for initial data binding of the grid.",
                            Title = "BLAZ-29015"
                        },
                        new
                        {
                            Id = 16,
                            Assignee = "Janet Leverling",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Close",
                            Summary = "Analyze stored procedures.",
                            Title = "BLAZ-29016"
                        },
                        new
                        {
                            Id = 17,
                            Assignee = "Nancy Davloio",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Validate",
                            Summary = "Validate editing issues.",
                            Title = "BLAZ-29017"
                        },
                        new
                        {
                            Id = 18,
                            Assignee = "Nancy Davloio",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Review",
                            Summary = "Test editing functionality.",
                            Title = "BLAZ-29018"
                        },
                        new
                        {
                            Id = 19,
                            Assignee = "Andrew Fuller",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Open",
                            Summary = "Enhance editing functionality.",
                            Title = "BLAZ-29019"
                        },
                        new
                        {
                            Id = 20,
                            Assignee = "Nancy Davloio",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            Summary = "Improve the performance of the editing functionality.",
                            Title = "BLAZ-29020"
                        },
                        new
                        {
                            Id = 21,
                            Assignee = "Steven walker",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Open",
                            Summary = "Arrange web meeting with the customer to show editing demo.",
                            Title = "BLAZ-29021"
                        },
                        new
                        {
                            Id = 22,
                            Assignee = "Janet Leverling",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Review",
                            Summary = "Fix the editing issues reported by the customer.",
                            Title = "BLAZ-29022"
                        },
                        new
                        {
                            Id = 23,
                            Assignee = "Steven walker",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Testing",
                            Summary = "Fix the issues reported by the customer.",
                            Title = "BLAZ-29023"
                        },
                        new
                        {
                            Id = 24,
                            Assignee = "Nancy Davloio",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Testing",
                            Summary = "Fix the issues reported in Safari browser.",
                            Title = "BLAZ-29024"
                        },
                        new
                        {
                            Id = 25,
                            Assignee = "Janet Leverling",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Testing",
                            Summary = "Fix the issues reported in data binding.",
                            Title = "BLAZ-29025"
                        },
                        new
                        {
                            Id = 26,
                            Assignee = "Nancy Davloio",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Testing",
                            Summary = "Test editing functionality.",
                            Title = "BLAZ-29026"
                        },
                        new
                        {
                            Id = 27,
                            Assignee = "Janet Leverling",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Testing",
                            Summary = "Test editing feature in the IE browser.",
                            Title = "BLAZ-29027"
                        });
                });

            modelBuilder.Entity("Entities.Models.MainProject", b =>
                {
                    b.Property<Guid>("MainProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MainProjectId");

                    b.ToTable("MainProjects");
                });

            modelBuilder.Entity("Entities.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Duration = "5days",
                            EndDate = new DateTime(2021, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 0,
                            StartDate = new DateTime(2021, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Product concept "
                        },
                        new
                        {
                            ProjectId = 2,
                            Duration = "3",
                            EndDate = new DateTime(2021, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1,
                            Progress = 30,
                            StartDate = new DateTime(2021, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Define the product usage"
                        },
                        new
                        {
                            ProjectId = 3,
                            EndDate = new DateTime(2021, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1,
                            Progress = 40,
                            TaskName = "Define the target audience"
                        },
                        new
                        {
                            ProjectId = 4,
                            Duration = "2",
                            ParentId = 1,
                            Progress = 30,
                            StartDate = new DateTime(2021, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Prepare product sketch and notes"
                        },
                        new
                        {
                            ProjectId = 5,
                            Duration = "0",
                            EndDate = new DateTime(2021, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 1,
                            Progress = 0,
                            StartDate = new DateTime(2021, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Concept approval"
                        },
                        new
                        {
                            ProjectId = 6,
                            Duration = "4",
                            EndDate = new DateTime(2021, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 30,
                            StartDate = new DateTime(2021, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Market research"
                        },
                        new
                        {
                            ProjectId = 7,
                            Duration = "4",
                            ParentId = 6,
                            Progress = 40,
                            TaskName = "Demand analysis"
                        },
                        new
                        {
                            ProjectId = 8,
                            Duration = "4",
                            EndDate = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 7,
                            Progress = 30,
                            StartDate = new DateTime(2021, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Customer strength"
                        },
                        new
                        {
                            ProjectId = 9,
                            Duration = "4",
                            EndDate = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 7,
                            Progress = 0,
                            StartDate = new DateTime(2021, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Market opportunity analysis"
                        },
                        new
                        {
                            ProjectId = 10,
                            Duration = "4",
                            EndDate = new DateTime(2021, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 6,
                            Progress = 30,
                            StartDate = new DateTime(2021, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Competitor analysis"
                        },
                        new
                        {
                            ProjectId = 11,
                            Duration = "4",
                            EndDate = new DateTime(2021, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 6,
                            Progress = 40,
                            StartDate = new DateTime(2021, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Product strength analysis"
                        },
                        new
                        {
                            ProjectId = 12,
                            Duration = "0",
                            EndDate = new DateTime(2021, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 6,
                            Progress = 30,
                            StartDate = new DateTime(2021, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Research completed"
                        },
                        new
                        {
                            ProjectId = 13,
                            Duration = "20",
                            EndDate = new DateTime(2021, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 0,
                            StartDate = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Product design and development"
                        },
                        new
                        {
                            ProjectId = 14,
                            Duration = "3",
                            EndDate = new DateTime(2021, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 13,
                            Progress = 30,
                            StartDate = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Functionality design"
                        },
                        new
                        {
                            ProjectId = 15,
                            Duration = "3",
                            EndDate = new DateTime(2021, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 13,
                            Progress = 40,
                            StartDate = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Quality design"
                        },
                        new
                        {
                            ProjectId = 16,
                            Duration = "2",
                            EndDate = new DateTime(2021, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 13,
                            Progress = 30,
                            StartDate = new DateTime(2021, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Define reliability"
                        },
                        new
                        {
                            ProjectId = 17,
                            Duration = "2",
                            EndDate = new DateTime(2021, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 13,
                            Progress = 0,
                            StartDate = new DateTime(2021, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Identifying raw materials"
                        },
                        new
                        {
                            ProjectId = 18,
                            Duration = "2",
                            EndDate = new DateTime(2021, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 13,
                            Progress = 30,
                            StartDate = new DateTime(2021, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Define cost plan"
                        },
                        new
                        {
                            ProjectId = 19,
                            Duration = "2",
                            EndDate = new DateTime(2021, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 18,
                            Progress = 40,
                            StartDate = new DateTime(2021, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Estimate manufacturing cost"
                        },
                        new
                        {
                            ProjectId = 20,
                            Duration = "2",
                            EndDate = new DateTime(2021, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 18,
                            Progress = 30,
                            StartDate = new DateTime(2021, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Estimate selling cost"
                        },
                        new
                        {
                            ProjectId = 21,
                            Duration = "7",
                            EndDate = new DateTime(2021, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 13,
                            Progress = 0,
                            StartDate = new DateTime(2021, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Development of final design"
                        },
                        new
                        {
                            ProjectId = 22,
                            Duration = "2",
                            EndDate = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 21,
                            Progress = 30,
                            StartDate = new DateTime(2021, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Develop dimensions and design"
                        },
                        new
                        {
                            ProjectId = 23,
                            Duration = "2",
                            EndDate = new DateTime(2021, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 21,
                            Progress = 40,
                            StartDate = new DateTime(2021, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Develop designs to meet industry"
                        },
                        new
                        {
                            ProjectId = 24,
                            Duration = "3",
                            EndDate = new DateTime(2021, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 21,
                            Progress = 30,
                            StartDate = new DateTime(2021, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Include all the details"
                        },
                        new
                        {
                            ProjectId = 25,
                            Duration = "3",
                            EndDate = new DateTime(2021, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 0,
                            StartDate = new DateTime(2021, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "CAD - Computer Aided Design"
                        },
                        new
                        {
                            ProjectId = 26,
                            Duration = "3",
                            EndDate = new DateTime(2021, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 30,
                            StartDate = new DateTime(2021, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "CAM - Computer Aided Manufacturing"
                        },
                        new
                        {
                            ProjectId = 27,
                            Duration = "0",
                            EndDate = new DateTime(2021, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 40,
                            StartDate = new DateTime(2021, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Finalize the design"
                        },
                        new
                        {
                            ProjectId = 28,
                            Duration = "4",
                            EndDate = new DateTime(2021, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 30,
                            StartDate = new DateTime(2021, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Prototype testing"
                        },
                        new
                        {
                            ProjectId = 29,
                            Duration = "4",
                            EndDate = new DateTime(2021, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 0,
                            StartDate = new DateTime(2021, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Include feedback"
                        },
                        new
                        {
                            ProjectId = 30,
                            Duration = "5",
                            EndDate = new DateTime(2021, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 30,
                            StartDate = new DateTime(2021, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Manufacturing"
                        },
                        new
                        {
                            ProjectId = 31,
                            Duration = "5",
                            EndDate = new DateTime(2021, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 40,
                            StartDate = new DateTime(2021, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Assembling material into finished goods"
                        },
                        new
                        {
                            ProjectId = 32,
                            Duration = "6",
                            EndDate = new DateTime(2021, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 30,
                            StartDate = new DateTime(2021, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Final product development"
                        },
                        new
                        {
                            ProjectId = 33,
                            Duration = "3",
                            EndDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 32,
                            Progress = 0,
                            StartDate = new DateTime(2021, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Important improvement"
                        },
                        new
                        {
                            ProjectId = 34,
                            Duration = "3",
                            EndDate = new DateTime(2021, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 32,
                            Progress = 30,
                            StartDate = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Customer testing and feedback"
                        },
                        new
                        {
                            ProjectId = 35,
                            Duration = "4",
                            EndDate = new DateTime(2021, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 40,
                            StartDate = new DateTime(2021, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Final product development"
                        },
                        new
                        {
                            ProjectId = 36,
                            Duration = "4",
                            EndDate = new DateTime(2021, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 35,
                            Progress = 30,
                            StartDate = new DateTime(2021, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Important improvement"
                        },
                        new
                        {
                            ProjectId = 37,
                            Duration = "4",
                            EndDate = new DateTime(2021, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 35,
                            Progress = 30,
                            StartDate = new DateTime(2021, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Address any unforeseen issues"
                        },
                        new
                        {
                            ProjectId = 38,
                            Duration = "8",
                            EndDate = new DateTime(2021, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 40,
                            StartDate = new DateTime(2021, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Finalize the product "
                        },
                        new
                        {
                            ProjectId = 39,
                            Duration = "4",
                            EndDate = new DateTime(2021, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 38,
                            Progress = 30,
                            StartDate = new DateTime(2021, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Branding the product"
                        },
                        new
                        {
                            ProjectId = 40,
                            Duration = "4",
                            EndDate = new DateTime(2021, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentId = 38,
                            Progress = 0,
                            StartDate = new DateTime(2021, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskName = "Marketing and presales"
                        });
                });

            modelBuilder.Entity("Entities.Models.ProjectResource", b =>
                {
                    b.Property<int>("ProjectResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectResourceId"));

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<double?>("Unit")
                        .HasColumnType("float");

                    b.HasKey("ProjectResourceId");

                    b.ToTable("ProjectResources");

                    b.HasData(
                        new
                        {
                            ProjectResourceId = 1,
                            ProjectId = 2,
                            ResourceId = 1,
                            Unit = 70.0
                        },
                        new
                        {
                            ProjectResourceId = 2,
                            ProjectId = 2,
                            ResourceId = 6
                        },
                        new
                        {
                            ProjectResourceId = 3,
                            ProjectId = 3,
                            ResourceId = 2
                        },
                        new
                        {
                            ProjectResourceId = 4,
                            ProjectId = 3,
                            ResourceId = 3
                        },
                        new
                        {
                            ProjectResourceId = 5,
                            ProjectId = 4,
                            ResourceId = 8
                        },
                        new
                        {
                            ProjectResourceId = 6,
                            Group = "Rose Fuller",
                            ProjectId = 4,
                            ResourceId = 9
                        },
                        new
                        {
                            ProjectResourceId = 7,
                            ProjectId = 6,
                            ResourceId = 4
                        },
                        new
                        {
                            ProjectResourceId = 8,
                            ProjectId = 7,
                            ResourceId = 4
                        },
                        new
                        {
                            ProjectResourceId = 9,
                            ProjectId = 7,
                            ResourceId = 8
                        },
                        new
                        {
                            ProjectResourceId = 10,
                            ProjectId = 8,
                            ResourceId = 12
                        },
                        new
                        {
                            ProjectResourceId = 11,
                            ProjectId = 8,
                            ResourceId = 5
                        });
                });

            modelBuilder.Entity("Entities.Models.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResourceId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            ResourceId = 1,
                            FirstName = "Martin",
                            FullName = "Martin Tamer",
                            LastName = "Tamer"
                        },
                        new
                        {
                            ResourceId = 2,
                            FirstName = "Rose",
                            FullName = "Rose Fuller",
                            LastName = "Fuller"
                        },
                        new
                        {
                            ResourceId = 3,
                            FirstName = "Margaret",
                            FullName = "Margaret Buchanan",
                            LastName = "Bunchanan"
                        },
                        new
                        {
                            ResourceId = 4,
                            FirstName = "Fuller",
                            FullName = "Fuller King",
                            LastName = "King"
                        },
                        new
                        {
                            ResourceId = 5,
                            FirstName = "Davolio",
                            FullName = "Davolio Fuller",
                            LastName = "Fuller"
                        },
                        new
                        {
                            ResourceId = 6,
                            FirstName = "Fuller",
                            FullName = "Fuller Buchanan",
                            LastName = "Bunchanan"
                        },
                        new
                        {
                            ResourceId = 7,
                            FirstName = "Jack",
                            FullName = "Jack Davolio",
                            LastName = "Davolio"
                        },
                        new
                        {
                            ResourceId = 8,
                            FirstName = "Tamer",
                            FullName = "Tamer Vinet",
                            LastName = "Vinet"
                        },
                        new
                        {
                            ResourceId = 9,
                            FirstName = "Vinnet",
                            FullName = "Vinet Fuller",
                            LastName = "Fuller"
                        },
                        new
                        {
                            ResourceId = 10,
                            FirstName = "Bergs",
                            FullName = "Bergs Anton",
                            LastName = "Anton"
                        },
                        new
                        {
                            ResourceId = 11,
                            FirstName = "Construction",
                            FullName = "Construction Supervisor",
                            LastName = "Supervisior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
